# Generated by Django 5.2.4 on 2025-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drsadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
