# Generated by Django 5.2.4 on 2025-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_drhamid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrAhmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(default='Unknown', max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrFaraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(default='Unknown', max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrImran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(default='Unknown', max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrNadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(default='Unknown', max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrSalman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(default='Unknown', max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrSara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petient_name', models.CharField(default='Unknown', max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Cell_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Dr_name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
