# Generated by Django 5.2.4 on 2025-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('cell_no', models.CharField(max_length=15)),
                ('test_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
